=== dcwebmaven/SocialNetworkDBXML/XMLFinalv3.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--Beginning of Root Element-->
<xs:element name="Friends">
     <xs:complexType>
     <xs:sequence>
     <!--Definition of Person Element-->
              <xs:element name="Person" minOccurs="0" maxOccurs="unbounded">
                   <xs:complexType>
                   <xs:sequence>
                      <xs:element minOccurs="1" maxOccurs="1" name="Social" type="SocialType"/>
                      <xs:element minOccurs="1" maxOccurs="1" name="First" type="xs:token"/>
                      <xs:element minOccurs="1" maxOccurs="1" name="Last" type="xs:token"/>
		      <xs:element minOccurs="0" maxOccurs="1" name="Birthday" type="BirthdayType"/>
                      <xs:element minOccurs="0" maxOccurs="unbounded" name="Phone" type="PhoneType"/>
                      <xs:element minOccurs="0" maxOccurs="unbounded" name="Address" type="AddressType"/> 
                      <xs:element minOccurs="0" maxOccurs="unbounded" name="Email" type="xs:token"/> 
                      <xs:element minOccurs="0" maxOccurs="unbounded" name="IM" type="IMType"/>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <!--End of Person Element-->
     </xs:sequence>
	 </xs:complexType>  

</xs:element>	
<!--End of Root Element-->

   <!--Defines Social Type-->
   
   <xs:complexType name="SocialType">
     <xs:simpleContent>
        <xs:extension base="xs:token">
           <xs:attribute name="Gender" type="GenderType" use="required"/>
        </xs:extension>
     </xs:simpleContent>
  </xs:complexType> 
  
      <!--Defines Gender Type and forces a male or female designtation-->
          <xs:simpleType name="GenderType">
            <xs:restriction base="xs:string">
            <xs:pattern value="Male|Female"/>
            </xs:restriction>
          </xs:simpleType>

           

                <!--Defines Phone Types and forces a type designation-->		 
                     <xs:complexType name="PhoneType">
                     <xs:simpleContent>
                     <xs:extension base="xs:token">
                       <xs:attribute name="Type" type="xs:token" use="required"/>
                     </xs:extension>
                     </xs:simpleContent>
                    </xs:complexType>
                    
                    
    
  <!--Defines Address Type parameters-->                  
  <xs:complexType name="AddressType">
    <xs:sequence> 
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Street" type="xs:token"/> 
      <xs:element minOccurs="0" maxOccurs="unbounded" name="City" type="xs:token"/> 
      <xs:element minOccurs="0" maxOccurs="unbounded" name="State" type="StateType"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="PostalCode" type="ZipType"/> 
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Country" type="xs:token"/> 
    </xs:sequence>
  </xs:complexType> 
					
	<!--Defines Birthday Type and restricts date to prior to 1995-->				
	<xs:simpleType name="BirthdayType">
	   <xs:restriction base="xs:date">
	      <xs:maxInclusive value="1995-01-01"/>
	   </xs:restriction>
	</xs:simpleType>
	
	<!--Defines StateType-->
	<xs:simpleType  name="StateType">
     <xs:restriction base="xs:string">
       <xs:pattern value="[A-Z][A-Z]"/>
     </xs:restriction>
   </xs:simpleType>
	
	<!--Defines ZipType-->
  <xs:simpleType name="ZipType">
     <xs:restriction base="xs:integer">
       <xs:pattern value="[0-9][0-9][0-9][0-9][0-9]"/>
     </xs:restriction>
   </xs:simpleType>

	<!--Defines IM Type-->
	<xs:complexType name="IMType">
     <xs:simpleContent>
        <xs:extension base="xs:token">
           <xs:attribute name="Service" type="IMServiceType" use="required"/>
        </xs:extension>
     </xs:simpleContent>
  </xs:complexType> 
  
  <!--Defines Service Type and restricts to known IM providers-->
   <xs:simpleType name="IMServiceType">
    <xs:restriction base="xs:token">
      <xs:enumeration value="AIM"/> 
      <xs:enumeration value="Google"/> 
      <xs:enumeration value="MSN"/>
      <xs:enumeration value="Yahoo"/> 
      <xs:enumeration value="Skype"/> 
      <xs:enumeration value="ICQ"/>
      <xs:enumeration value="Facebook"/>
      <xs:enumeration value="AOL"/>
      <xs:enumeration value="Jabber"/>
    </xs:restriction>
  </xs:simpleType>
	

</xs:schema>

=== dcwebmaven/SocialNetworkDBXML/XMLFinalv3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="SocialNetworkv3.xsl" type="text/xsl"?>
<!DOCTYPE Friends>
<Friends xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLFinalv3.xsd">
<Person>
   <Social Gender="Female">Friend</Social>
   <First>Diana</First>
   <Last>Prince</Last>
   <Birthday>1969-05-25</Birthday>
   <Phone Type="Home">202-555-1212</Phone>
     <Address>
       <Street>414 10th Street NW</Street>
       <City>Washington</City>
       <State>DC</State>
       <PostalCode>20012</PostalCode>
       <Country>US</Country>
     </Address>
     <Email>wwjl@gmail.com</Email>
     <IM Service="AOL">wonderw</IM>
</Person>
<Person>
  <Social Gender="Male">Work</Social>
  <First>Steve</First>
  <Last>Trevor</Last>
  <Birthday>1945-09-17</Birthday>
  <Phone Type="Work">202-453-6868</Phone>
  <Address>
      <Street>2400 Nebraska Ave. NW</Street>
      <City>Washington</City>
      <State>DC</State>
      <PostalCode>20017</PostalCode>
      <Country>US</Country>
  </Address>
  <Email>jschurch123@gmail.com</Email>
  <IM Service="AIM">morph</IM>
</Person>
<Person>
  <Social Gender="Female">Ally</Social>
  <First>Amanda</First>
  <Last>King</Last>
  <Birthday>1960-07-22</Birthday>
  <Phone Type="Home">703-555-1414</Phone>
  <Address>
      <Street>414 25th Street</Street>
      <City>Arlington</City>
      <State>VA</State>
      <PostalCode>22205</PostalCode>
      <Country>US</Country>
  </Address>
  <Email>mrsking@yahoo.com</Email>
  <IM Service="Jabber">supermom</IM>
</Person>
<Person>
  <Social Gender="Male">Family</Social>
  <First>Lee</First>
  <Last>Stetson</Last>
  <Birthday>1957-05-05</Birthday>
  <Phone Type="Cell">202-656-1312</Phone>
  <Address>
      <Street>2425 Massachusetts Ave. NW</Street>
      <City>Washington</City>
      <State>DC</State>
      <PostalCode>20010</PostalCode>
      <Country>US</Country>
  </Address>
  <Email>scarecrow@aol.com</Email>
  <IM Service="Google">scarecrow</IM>
</Person>
<Person>
  <Social Gender="Male">Friend</Social>
  <First>Popeye</First>
  <Last>Sailorman</Last>
  <Birthday>1925-05-17</Birthday>
  <Phone Type="Home">202-656-1333</Phone>
  <Address>
      <Street>3131 Massachusetts Ave. NW</Street>
      <City>Washington</City>
      <State>DC</State>
      <PostalCode>20010</PostalCode>
      <Country>US</Country>
  </Address>
  <Email>spinach@aol.com</Email>
  <IM Service="Google">popeye</IM>
</Person>
</Friends>
